# Generated by Django 6.0 on 2026-01-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrizione del servizio'),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.CharField(default='a partire da 50€', max_length=50, verbose_name='Prezzo'),
        ),
    ]
